import type { MetadataRoute } from "next";

/**
 * App manifest generated by Next.js (served at /manifest.webmanifest with the
 * correct `application/manifest+json` content-type and correctly resolved
 * relative icon URLs). This is what Chrome needs to show "Install app".
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Play Points Tracker",
    short_name: "Play Points",
    description:
      "Track Google Play Points across multiple Gmail accounts — weekly claims, quest rewards, purchase bonuses and redemptions.",
    id: "/",
    start_url: "/?utm_source=pwa",
    scope: "/",
    display: "standalone",
    display_override: ["standalone", "minimal-ui"],
    orientation: "any",
    lang: "en",
    background_color: "#f6f8fc",
    theme_color: "#f6f8fc",
    categories: ["finance", "productivity", "utilities"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
